rzgl2: tf-a: switch to version with improved eMMC init timeout
prevent boot failures with the error message:
ERROR:   BL2: emmc err:func_no=0x4 code=0x10